"""Static data for :mod:`inspector_widget.normalize` (spec section 3.7).

Two tables, both plain data (no imports, cheap to load):

``STATIC_VIEW_DEFAULTS``
    Per class family, the value a View property has when nothing set it. A
    property whose (normalized) value equals the family default is "default" and
    is hidden, and counted, by brief output. Values are in normalized form:
    colours are ``#AARRGGBB``, GRAVITY/INT_FLAG are the agent's ``|``-joined labels,
    and a tuple lists alternative defaults. The legacy MCP shape (E3) loses the
    labels and reports GRAVITY/INT_FLAG as ``0``; ``0`` is accepted too.
    ``transformPivotX``/``transformPivotY`` default to the view's centre and are
    checked against its bounds, not listed here.

    Derived from the View screen of the a11yprobe app, captured live on
    emulator-5554 (API 37, 480 dpi; scratchpad/live/scen_f/dump_props.json: 40
    views, 169 property names), and from the framework defaults of
    View/ViewGroup/LinearLayout/FrameLayout/ScrollView/TextView/ImageView/
    CompoundButton. Re-recorded (WP L1) from a11yprobe's ViewDefaultsActivity on
    emulator-5558 (API 37, 480 dpi, Material3 DayNight theme): bare View,
    FrameLayout, LinearLayout, ScrollView, TextView, ImageView, Button, EditText,
    CheckBox and Switch, constructed in code (framework classes) and inflated
    with no attributes (MaterialTextView, AppCompatImageView, MaterialButton,
    AppCompatEditText, MaterialCheckBox); fixture
    ``tests/fixtures/captures/a11yprobe_view_defaults``. What still differs on
    those bare widgets is theme- or density-dependent (text colours and size,
    drawables, dp-based sizes and paddings), so it stays out of this table and
    is left to the per-capture majority rule.

``LIBRARY_FILES``
    Basenames (without ``.kt``) of the Kotlin files in the Jetpack Compose
    runtime, ui, foundation, animation, material and material3 libraries that
    define composables. A slot-table group whose ``source`` file is one of these is
    library code. Generated by ``host/tests/gen_library_files.py`` from the local
    Gradle cache: every ``*-sources.jar`` file containing ``@Composable``, plus the
    ``SourceFile`` of every class in the artifacts' AAR/JAR whose constant pool
    references ``androidx/compose/runtime/Composer`` (which covers versions
    cached without sources). Compose 1.9-1.12 and material3 1.3-1.5 were cached
    when this was generated.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Class families. normalize.class_family() maps a View to one of these; a lookup
# walks FAMILY_PARENTS up to "View".
# --------------------------------------------------------------------------- #
FAMILY_PARENTS = {
    "View": None,
    "ViewGroup": "View",
    "LinearLayout": "ViewGroup",
    "FrameLayout": "ViewGroup",
    "ScrollView": "FrameLayout",
    "TextView": "View",
    "Button": "TextView",
    "EditText": "TextView",
    "CompoundButton": "Button",
    "ImageView": "View",
}

INT_MAX = 2147483647
_GRAVITY_TOP_START = ("top|start", 0)
_UNSPECIFIED_GRAVITY = ("fill|clip_vertical|clip_horizontal", -1, 0)
_BLACK = "#FF000000"
_TRANSPARENT = "#00000000"

STATIC_VIEW_DEFAULTS = {
    "View": {
        "accessibilityFocused": False,
        "accessibilityHeading": False,
        "accessibilityLiveRegion": "none",
        "activated": False,
        "alpha": 1.0,
        "baseline": -1,
        "clickable": False,
        "contextClickable": False,
        "defaultFocusHighlightEnabled": True,
        "drawingCacheQuality": "auto",
        "duplicateParentState": False,
        "elevation": 0.0,
        "enabled": True,
        "fadingEdgeLength": 0,
        "filterTouchesWhenObscured": False,
        "fitsSystemWindows": False,
        "focusable": "auto",
        "focusableInTouchMode": False,
        "focused": False,
        "focusedByDefault": False,
        "forceDarkAllowed": True,
        "foregroundGravity": _GRAVITY_TOP_START,
        "hapticFeedbackEnabled": True,
        "importantForAccessibility": "auto",
        "importantForAutofill": "auto",
        "importantForContentCapture": "auto",
        "isScrollContainer": False,
        "keepScreenOn": False,
        "keyboardNavigationCluster": False,
        "layerType": "none",
        "layoutDirection": "ltr",
        "longClickable": False,
        "minHeight": 0,
        "minWidth": 0,
        "nestedScrollingEnabled": False,
        "outlineAmbientShadowColor": _BLACK,
        "outlineSpotShadowColor": _BLACK,
        "overScrollMode": "ifContentScrolls",
        "paddingBottom": 0,
        "paddingLeft": 0,
        "paddingRight": 0,
        "paddingTop": 0,
        "paddingStart": 0,
        "paddingEnd": 0,
        "pressed": False,
        "rawLayoutDirection": "inherit",
        "rawTextAlignment": "gravity",
        "rawTextDirection": "inherit",
        "requiresFadingEdge": ("none", 0),
        "rotation": 0.0,
        "rotationX": 0.0,
        "rotationY": 0.0,
        "saveEnabled": True,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "screenReaderFocusable": False,
        "scrollIndicators": ("none", 0),
        "scrollX": 0,
        "scrollY": 0,
        "scrollbarDefaultDelayBeforeFade": 300,
        "scrollbarFadeDuration": 250,
        "scrollbarSize": 12,
        "scrollbarStyle": "insideOverlay",
        "selected": False,
        "solidColor": (_TRANSPARENT, 0),
        "soundEffectsEnabled": True,
        "textAlignment": "gravity",
        "textDirection": "firstStrong",
        "transitionGroup": False,
        "translationX": 0.0,
        "translationY": 0.0,
        "translationZ": 0.0,
        "visibility": "visible",
        # layout params (is_layout=true)
        "layout_gravity": _UNSPECIFIED_GRAVITY,
        "layout_marginBottom": 0,
        "layout_marginLeft": 0,
        "layout_marginRight": 0,
        "layout_marginTop": 0,
        "layout_marginStart": 0,
        "layout_marginEnd": 0,
        "layout_weight": 0.0,
    },
    "ViewGroup": {
        "addStatesFromChildren": False,
        "alwaysDrawnWithCache": True,
        "animationCache": True,
        "clipChildren": True,
        "clipToPadding": True,
        "descendantFocusability": "beforeDescendants",
        "layoutMode": "clipBounds",
        "persistentDrawingCache": "scrolling",
        "splitMotionEvents": True,
        "touchscreenBlocksFocus": False,
    },
    "LinearLayout": {
        "baselineAligned": True,
        "baselineAlignedChildIndex": -1,
        "gravity": _GRAVITY_TOP_START,
        "measureWithLargestChild": False,
        "orientation": "horizontal",
        "weightSum": -1.0,
    },
    "FrameLayout": {
        "measureAllChildren": False,
    },
    "ScrollView": {
        "descendantFocusability": "afterDescendants",
        "fillViewport": False,
        "focusable": ("true", "auto"),
        "isScrollContainer": True,
        "scrollbarDefaultDelayBeforeFade": (400, 300),
    },
    "TextView": {
        # a TextView makes itself important for accessibility, autofill and
        # content capture; "auto" on older platforms
        "importantForAccessibility": ("yes", "auto"),
        "importantForAutofill": ("yes", "auto"),
        "importantForContentCapture": ("yes", "auto"),
        "text": (None, ""),
        "autoLink": ("none", 0, ""),
        "autoSizeMaxTextSize": -1,
        "autoSizeMinTextSize": -1,
        "autoSizeStepGranularity": -1,
        "autoSizeTextType": "none",
        "breakStrategy": "high_quality",
        "cursorVisible": True,
        "drawablePadding": 0,
        "elegantTextHeight": True,
        "ellipsize": ("none", None),
        "fallbackLineSpacing": True,
        "freezesText": False,
        "gravity": _GRAVITY_TOP_START,
        "hyphenationFrequency": "none",
        "imeActionId": 0,
        "imeOptions": ("normal|actionUnspecified", 0),
        "includeFontPadding": True,
        "inputType": ("none", 0),
        "justificationMode": "none",
        "letterSpacing": 0.0,
        "lineSpacingExtra": 0.0,
        "lineSpacingMultiplier": 1.0,
        "linksClickable": True,
        "marqueeRepeatLimit": 3,
        "maxEms": -1,
        "maxHeight": -1,
        "maxLines": INT_MAX,
        "maxWidth": INT_MAX,
        "minEms": -1,
        "minLines": (0, -1),
        "scrollHorizontally": False,
        "shadowColor": (_TRANSPARENT, 0),
        "shadowDx": 0.0,
        "shadowDy": 0.0,
        "shadowRadius": 0.0,
        "singleLine": False,
        "textAllCaps": False,
        "textIsSelectable": False,
        "textScaleX": 1.0,
    },
    "Button": {
        "textAllCaps": (True, False),  # android.widget.Button caps, MaterialButton not
        "breakStrategy": "simple",
        "clickable": True,
        "focusable": "true",
        "gravity": ("center", "center_vertical|center_horizontal"),
    },
    "EditText": {
        "defaultFocusHighlightEnabled": (False, True),
        "inputType": ("textMultiLine|text", "text|textMultiLine"),
        "breakStrategy": "simple",
        "focusable": "true",
        "focusableInTouchMode": True,
        "clickable": True,
        "longClickable": True,
        "freezesText": True,
        "gravity": ("start|center_vertical", "center_vertical|start", "center_vertical"),
    },
    "CompoundButton": {
        "checked": False,
        "gravity": ("start|center_vertical", "center_vertical|start", "center_vertical"),
        "showText": False,
        "splitTrack": False,
        "switchMinWidth": 0,
        "switchPadding": 0,
        "thumbTextPadding": 0,
    },
    "ImageView": {
        "importantForAutofill": ("no", "auto"),
        "importantForContentCapture": ("yes", "auto"),
        "adjustViewBounds": False,
        "baselineAlignBottom": False,
        "cropToPadding": False,
        "maxHeight": INT_MAX,
        "maxWidth": INT_MAX,
        "scaleType": "fitCenter",
    },
}

#: Properties never hidden by the per-capture class-majority rule (identity and
#: state: the values an agent is usually looking for).
MAJORITY_EXEMPT = frozenset({
    "text", "contentDescription", "hint", "id", "labelFor", "tooltipText",
    "stateDescription", "paneTitle", "checked", "enabled", "clickable", "longClickable",
    "focusable", "visibility", "screenReaderFocusable", "accessibilityHeading",
    "accessibilityLiveRegion", "selected", "activated", "alpha", "minHeight", "minWidth",
    "layout_width", "layout_height",
})

#: Properties derived from others (font metrics), not set by the developer. Brief
#: output treats them as defaults; textSize and lineHeight stay visible.
DERIVED_PROPS = frozenset({"baseline", "firstBaselineToTopHeight", "lastBaselineToBottomHeight"})

_LIBRARY_FILES = """
AccessibilityServiceStateProvider AccessibilityServiceStateProvider.android ActualJvm.jvm
AlertDialog AnchoredDraggable AndroidActualDefaultDecayAnimationSpec.android
AndroidAlertDialog.android AndroidCompositionLocals.android AndroidCursorHandle.android
AndroidDialog.android AndroidExternalSurface.android AndroidMenu.android
AndroidOverscroll.android AndroidPopup.android AndroidPosture.android
AndroidSelectionHandles.android AndroidTextContextMenuToolbarProvider.android
AndroidView.android AndroidWindowAdaptiveInfo.android Animatable AnimateAsState
AnimatedContent AnimatedShape AnimatedVisibility AnimationSearch.android
AnnotatedStringResolveInlineContent AppBar AppBarColumn AppBarDsl AppBarRow BackHandler
BackHandler.android BackdropScaffold Badge BasicEdgeToEdgeDialog
BasicEdgeToEdgeDialog.android BasicSecureTextField BasicSecureTextField.android BasicText
BasicText.android BasicTextContextMenuProvider BasicTextField BasicTooltip
BasicTooltip.android BottomNavigation BottomSheetScaffold Box BoxWithConstraints Button
ButtonGroup CalendarLocale CalendarLocale.android Canvas Card Carousel CarouselItemScope
CarouselState Checkbox Chip Clickable ClickableText ClipboardEventsHandler
ClipboardEventsHandler.jvmAndAndroid ColorResources.android ColorScheme Colors Column
CommonContextMenuArea CommonRipple Composable ComposableInvoker.jvm
ComposableInvoker.jvmAndAndroid ComposableLambda ComposableLambda.jvm
ComposableLambda.jvmAndAndroid ComposableLambdaN.jvm ComposableLambdaN.jvmAndAndroid
ComposableMethod.jvm ComposableMethod.jvmAndAndroid Composables ComposeToolingFlags
ComposeView.android ComposeViewAdapter.android ComposeViewContext.android ComposedModifier
Composer Composition CompositionContext CompositionLocal CompositionLocals ContentAlpha
ContextMenu ContextMenu.android ContextMenuArea ContextMenuArea.android ContextMenuStrings
ContextMenuStrings.android ContextMenuUi ContextMenuUi.android ContextualFlowLayout
CoreTextField Crossfade DarkTheme DarkTheme.android DateInput DatePicker DatePicker.jvm
DatePicker.jvmAndAndroid DatePickerDialog DatePickerDialog.android DateRangeInput
DateRangePicker DefaultDecayAnimationSpec DefaultTextContextMenuDropdownProvider.android
Dialog Divider DragAndDropHoverInteraction DragHandle DragInteraction Draggable Draggable2D
Drawer Effects ElevationOverlay EnterExitTransition Expect.jvm Expect.jvmAndAndroid
ExposedDropdownMenu ExposedDropdownMenu.android ExposedDropdownMenuPopup
ExposedDropdownMenuPopup.android ExpressiveNavigationBar FlexBox FloatingActionButton
FloatingActionButtonMenu FloatingToolbar FlowLayout FlowLayoutOverflow FocusInteraction
FontResources.android GapComposer GraphicsLayerScope Grid HeightInLinesModifier
HoverInteraction Icon IconButton IconButtonDefaults Image ImageResources.android Indication
InfiniteTransition InlineTextContent Inspectable.android Label Layout LazyDsl LazyGrid
LazyGridBeyondBoundsModifier LazyGridDsl LazyGridIntervalContent LazyGridItemProvider
LazyGridSnapLayoutInfoProvider LazyGridState LazyLayout LazyLayoutBeyondBoundsModifierLocal
LazyLayoutBringIntoViewSpec LazyLayoutItemContentFactory LazyLayoutItemProvider
LazyLayoutPager LazyLayoutPinnableItem LazyLayoutSemantics LazyList LazyList.android
LazyListBeyondBoundsModifier LazyListIntervalContent LazyListItemProvider LazyListSemantics
LazyListSnapLayoutInfoProvider LazyListState LazySaveableStateHolder LazySemantics
LazyStaggeredGrid LazyStaggeredGridBeyondBoundsModifier LazyStaggeredGridDsl
LazyStaggeredGridIntervalContent LazyStaggeredGridItemProvider
LazyStaggeredGridMeasurePolicy LazyStaggeredGridSemantics LazyStaggeredGridState
LinkComposer ListItem ListItemDefaults LoadingIndicator LocalRetainedValuesStore
LookaheadAnimationVisualDebugHelper LookaheadScope ManagedRetainedValuesStore MaterialShapes
MaterialTextSelectionColors MaterialTheme MaterialTheme.android MediaQuery
MediaQuery.android Menu MenuDefaults ModalBottomSheet ModalBottomSheet.android MotionScheme
MovableContent MultiAspectCarousel NavigationBar NavigationDrawer NavigationDrawer.android
NavigationItem NavigationRail NestedScrollInteropConnection.android OutlinedTextField
Overscroll Pager PagerBeyondBoundsModifier PagerMeasurePolicy PagerSemantics PagerState
PainterResources.android PausableComposition PlatformDefaultTextContextMenuProviders.android
PlatformSelectionBehaviors PlatformSelectionBehaviors.android PlatformTextInputModifierNode
PointerInteropFilter.android Popup PrecisionPointer PrecisionPointer.android
PrefetchScheduler PrefetchScheduler.android PressInteraction PreviewActivity.android
PreviewUtils.android PreviewWrapper PrimitiveResources.android ProduceState
ProgressIndicator ProvideContentColorTextStyle
ProvideDefaultPlatformTextContextMenuProviders PullRefreshIndicator PullRefreshState
PullToRefresh RadioButton RecomposeScopeImpl Recomposer RectListDebugger.android
RememberSaveable RememberSerializable Resources.android Retain RetainedEffect
RetainedValuesStoreRegistry Ripple Ripple.android RippleTheme Row SafeCollector.common
SaveableStateHolder Scaffold Scrim Scroll Scrollable Scrollable.android Scrollable2DState
ScrollableState ScrollingContainer SearchBar SearchBar.android SecureTextField
SegmentedButton Selectable SelectionContainer SelectionHandles SelectionMagnifier
SelectionManager.android SelectionState Shapes SharedTransitionScope SheetDefaults
ShortNavigationBar SimpleLayout SingleValueAnimation Slider Snackbar SnackbarHost
SnapFlingBehavior SnapshotFlow SnapshotState SoundEffectOnInteraction.android Spacer
SplineBasedFloatDecayAnimationSpec.android SplitButton StringResources.android Strings
Strings.android StyleState SubcomposeLayout Surface SwipeToDismiss SwipeToDismissBox
Swipeable Switch SystemBarsDefaultInsets SystemBarsDefaultInsets.android Tab TabRow
TestModifierUpdater Text TextField TextFieldCursor TextFieldDecorator TextFieldDefaults
TextFieldImpl TextFieldKeyInput TextFieldPointerModifier.android
TextFieldPointerModifier.common TextFieldPressGestureFilter TextFieldScroll
TextFieldScroll.android TextFieldSelectionManager TextFieldSelectionManager.android
TextFieldSize TextFieldState TextLinkScope TextMeasurerHelper TimeFormat TimeFormat.android
TimePicker TimePicker.android TimePickerDialog ToggleButton Toggleable Tooltip
Tooltip.android TransformableState Transition Typography UiComposable Utils Utils.jvm
Utils.nonJvm VectorComposable VectorCompose VectorPainter VectorResources.android
WavyProgressIndicator WideNavigationRail WideNavigationRail.android WideNavigationRailState
WindowAdaptiveInfo WindowInfo WindowInsets WindowInsets.android
WindowInsetsConnection.android WindowInsetsPadding WindowInsetsPadding.android
Wrapper.android
"""

LIBRARY_FILES = frozenset(_LIBRARY_FILES.split())
