#!/usr/bin/env bash
# Regenerate the Python protobuf bindings for Inspector Widget.
#
# Produces host/inspector_widget/proto/view_inspection_pb2.py from the FINAL
# protocol at proto/view_inspection.proto. The generated file is checked in, so
# you only need this after changing the .proto.
#
# The protoc version matters. Python gencode is stamped with the protobuf
# release that produced it and refuses to import under an older runtime or a
# different major (ValidateProtobufRuntimeVersion). protoc 33.x emits 6.33.x
# gencode; protoc 34+ emits 7.x gencode, which the pinned runtime
# (protobuf>=6.33.5,<7 in requirements.txt / pyproject.toml) cannot import. So
# this script reads the protoc release the checked-in file was built with (its
# "Protobuf Python Version: 6.<N>.x" header means protoc <N>.x) and refuses to
# run any other protoc major.
#
# protoc comes from $PROTOC if set (it may be a command with arguments), else
# `protoc` on PATH. A matching protoc without a system install:
#   python3 -m venv /tmp/pt && /tmp/pt/bin/pip install 'grpcio-tools==1.81.0'   # bundles protoc 33.5
#   PROTOC="/tmp/pt/bin/python -m grpc_tools.protoc" host/generate_proto.sh
#
# Moving to a new protobuf major on purpose? Run with ALLOW_PROTOC_MISMATCH=1,
# then raise the protobuf runtime pins to match the new gencode header.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

PROTO_DIR="$REPO_ROOT/proto"
PROTO_FILE="$PROTO_DIR/view_inspection.proto"
OUT_DIR="$HERE/inspector_widget/proto"
PB2="$OUT_DIR/view_inspection_pb2.py"

die() { echo "error: $*" >&2; exit 1; }

# --- the protoc release the checked-in gencode was built with -----------------
[ -f "$PB2" ] || die "$PB2 is missing. It is tracked in git and records which protoc
the pinned runtime needs; restore it first:
  git checkout -- host/inspector_widget/proto/view_inspection_pb2.py"
GENCODE_VERSION="$(sed -n 's/^# Protobuf Python Version: \([0-9][0-9.]*\).*/\1/p' "$PB2" | head -1)"
[ -n "$GENCODE_VERSION" ] || die "no '# Protobuf Python Version:' header in $PB2"
# Python protobuf X.Y.Z is generated by protoc Y.Z, so the protoc major is Y.
EXPECTED_MAJOR="$(echo "$GENCODE_VERSION" | cut -d. -f2)"

# --- the protoc we were given ---------------------------------------------------
PROTOC="${PROTOC:-protoc}"
read -r -a PROTOC_CMD <<< "$PROTOC"
command -v "${PROTOC_CMD[0]}" >/dev/null 2>&1 \
  || die "protoc not found ('$PROTOC'). Install protoc $EXPECTED_MAJOR.x or set PROTOC (see the header of this script)."
PROTOC_VERSION="$("${PROTOC_CMD[@]}" --version 2>&1 | sed -n 's/^libprotoc \([0-9][0-9.]*\).*/\1/p' | head -1)"
[ -n "$PROTOC_VERSION" ] || die "could not read a version from '$PROTOC --version'"
FOUND_MAJOR="${PROTOC_VERSION%%.*}"

if [ "$FOUND_MAJOR" != "$EXPECTED_MAJOR" ]; then
  if [ "${ALLOW_PROTOC_MISMATCH:-0}" = "1" ]; then
    echo "warning: using protoc $PROTOC_VERSION (checked-in gencode is from protoc $EXPECTED_MAJOR.x);" \
         "update the protobuf runtime pins to match the new gencode header." >&2
  else
    cat >&2 <<EOF
error: protoc $PROTOC_VERSION does not match the checked-in bindings.
  $PB2
  was generated by protoc $EXPECTED_MAJOR.x (Python gencode $GENCODE_VERSION), and the host pins
  the runtime to protobuf>=6.33.5,<7. Gencode from protoc $PROTOC_VERSION needs a different
  runtime, so the package would fail to import with a VersionError.
Use protoc $EXPECTED_MAJOR.x, e.g. without a system install:
  python3 -m venv /tmp/pt && /tmp/pt/bin/pip install 'grpcio-tools==1.81.0'   # bundles protoc 33.5
  PROTOC="/tmp/pt/bin/python -m grpc_tools.protoc" $0
(Deliberately moving to a new protobuf major? Re-run with ALLOW_PROTOC_MISMATCH=1 and
raise the protobuf pins in host/requirements.txt and host/pyproject.toml.)
EOF
    exit 1
  fi
fi

mkdir -p "$OUT_DIR"

# The generated module imports the bare name `view_inspection_pb2`; placing it
# in the proto package (which is on sys.path via the package) resolves it.
"${PROTOC_CMD[@]}" \
  --proto_path="$PROTO_DIR" \
  --python_out="$OUT_DIR" \
  "$PROTO_FILE"

# Ensure the package marker exists.
if [ ! -f "$OUT_DIR/__init__.py" ]; then
  cat > "$OUT_DIR/__init__.py" <<'EOF'
"""Generated protocol buffer bindings for Inspector Widget."""
EOF
fi

echo "generated $PB2 with protoc $PROTOC_VERSION"
