# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skia.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'skia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nskia.proto\x12\x15layoutinspector.proto\x1a\x1bgoogle/protobuf/empty.proto\"T\n\x11RequestedNodeInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x01(\x11\x12\t\n\x01y\x18\x03 \x01(\x11\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\"\x98\x01\n\x12GetViewTreeRequest\x12\x0b\n\x03skp\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x41\n\x0frequested_nodes\x18\x03 \x03(\x0b\x32(.layoutinspector.proto.RequestedNodeInfo\x12\r\n\x05scale\x18\x04 \x01(\x02\x12\x12\n\ntotal_size\x18\x06 \x01(\x05\"\xa6\x02\n\rInspectorView\x12\x1a\n\x0eid_for_v0_only\x18\x01 \x01(\tB\x02\x18\x01\x12!\n\x15timestamp_for_v0_only\x18\x02 \x01(\x03\x42\x02\x18\x01\x12\x1c\n\x10type_for_v0_only\x18\x03 \x01(\tB\x02\x18\x01\x12\x19\n\rx_for_v0_only\x18\x04 \x01(\x05\x42\x02\x18\x01\x12\x19\n\ry_for_v0_only\x18\x05 \x01(\x05\x42\x02\x18\x01\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\x12\r\n\x05image\x18\x08 \x01(\x0c\x12\x36\n\x08\x63hildren\x18\t \x03(\x0b\x32$.layoutinspector.proto.InspectorView\x12\n\n\x02id\x18\n \x01(\x03\x12\x10\n\x08image_id\x18\x0b \x01(\x05\"j\n\x13GetViewTreeResponse\x12\x32\n\x04root\x18\x01 \x01(\x0b\x32$.layoutinspector.proto.InspectorView\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x10\n\x08image_id\x18\x03 \x01(\x05\x32\xe0\x02\n\x11SkiaParserService\x12\x66\n\x0bGetViewTree\x12).layoutinspector.proto.GetViewTreeRequest\x1a*.layoutinspector.proto.GetViewTreeResponse\"\x00\x12k\n\x0cGetViewTree2\x12).layoutinspector.proto.GetViewTreeRequest\x1a*.layoutinspector.proto.GetViewTreeResponse\"\x00(\x01\x30\x01\x12\x38\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x08Shutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42:\n,com.android.tools.idea.layoutinspector.protoB\nSkiaParserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.android.tools.idea.layoutinspector.protoB\nSkiaParser'
  _globals['_INSPECTORVIEW'].fields_by_name['id_for_v0_only']._loaded_options = None
  _globals['_INSPECTORVIEW'].fields_by_name['id_for_v0_only']._serialized_options = b'\030\001'
  _globals['_INSPECTORVIEW'].fields_by_name['timestamp_for_v0_only']._loaded_options = None
  _globals['_INSPECTORVIEW'].fields_by_name['timestamp_for_v0_only']._serialized_options = b'\030\001'
  _globals['_INSPECTORVIEW'].fields_by_name['type_for_v0_only']._loaded_options = None
  _globals['_INSPECTORVIEW'].fields_by_name['type_for_v0_only']._serialized_options = b'\030\001'
  _globals['_INSPECTORVIEW'].fields_by_name['x_for_v0_only']._loaded_options = None
  _globals['_INSPECTORVIEW'].fields_by_name['x_for_v0_only']._serialized_options = b'\030\001'
  _globals['_INSPECTORVIEW'].fields_by_name['y_for_v0_only']._loaded_options = None
  _globals['_INSPECTORVIEW'].fields_by_name['y_for_v0_only']._serialized_options = b'\030\001'
  _globals['_REQUESTEDNODEINFO']._serialized_start=66
  _globals['_REQUESTEDNODEINFO']._serialized_end=150
  _globals['_GETVIEWTREEREQUEST']._serialized_start=153
  _globals['_GETVIEWTREEREQUEST']._serialized_end=305
  _globals['_INSPECTORVIEW']._serialized_start=308
  _globals['_INSPECTORVIEW']._serialized_end=602
  _globals['_GETVIEWTREERESPONSE']._serialized_start=604
  _globals['_GETVIEWTREERESPONSE']._serialized_end=710
  _globals['_SKIAPARSERSERVICE']._serialized_start=713
  _globals['_SKIAPARSERSERVICE']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
